CREATE TABLE iPurchase.MyItemALL AS (
WITH 
MOQPURCHASES AS(
	SELECT PM.COMPANYID, PM.SUBSIDIARYID, PM.ITEMID, MOQs.MOQ AS MOQs, 0 AS ORDERTYPE FROM
	(SELECT COMPANYID, SUBSIDIARYID, ITEMID FROM iPurchase.PURCHPRICE_master_Filtered) AS PM
	LEFT JOIN
	(SELECT COMPANYID, SUBSIDIARYID, ITEMID, MOQ FROM fersadv.Item_ALL) AS MOQs
	ON PM.COMPANYID = MOQs.COMPANYID AND PM.SUBSIDIARYID = MOQs.SUBSIDIARYID AND PM.ITEMID = MOQs.ITEMID
),
MOQROUTES AS (
	SELECT COMPANYID, SUBSIDIARYID, ITEMID,
	CASE LINEROUTEID
	    WHEN 'ZI' THEN 700
	    WHEN 'ZC' THEN 700
	    WHEN 'ZB' THEN 700
	    WHEN 'Z3' THEN 300
	    WHEN 'Z2' THEN 500
	    WHEN 'Z1' THEN 700
	    WHEN 'Z0-CP' THEN 700
	    WHEN 'Z0-CG' THEN 700
	    WHEN 'Z0-A' THEN 700
	    WHEN 'LASER-KITS' THEN 1
	    WHEN 'LASER-3' THEN 1
	    WHEN 'LASER-2' THEN 1
	    WHEN 'LASER-1' THEN 1
	    WHEN 'BIKONE' THEN 1
	    WHEN 'B2Z-RW' THEN 1
	    WHEN 'B2Z-FW' THEN 1
	    WHEN 'B1Z-RT' THEN 1
	    WHEN 'B1Z-RM' THEN 1
	    WHEN 'B1Z-KRBC' THEN 1
	    ELSE NULL -- It will be null for the values coming from LINEROUTEID = ''
	END AS MOQs, 1 AS ORDERTYPE
	FROM iPurchase.ROUTES_master_Filtered
),
UNIONED AS (
	SELECT *, ROW_NUMBER() OVER() AS RN FROM MOQPURCHASES
	UNION ALL
	SELECT *, ROW_NUMBER() OVER() AS RN FROM MOQROUTES
),
FINAL AS (
	SELECT *, 
	CASE 
	    WHEN LEFT(ITEMID, 3) = '420' THEN FLOOR(RANDOM()*(40000-0)+0)
	    ELSE FLOOR(RANDOM()*(2000-0)+0)
	END AS STOCK
	FROM UNIONED
),
FINAL_WITH_RANDOM AS (
	SELECT *, RANDOM() AS RAND FROM FINAL
),
FINAL_STOCK AS (
	SELECT COMPANYID, SUBSIDIARYID, ITEMID, MOQs, ORDERTYPE, 
	CASE 
	    WHEN RAND <= 0.25 THEN 0
	    ELSE STOCK
	END AS STOCK
	FROM FINAL_WITH_RANDOM
)
SELECT *
FROM FINAL_STOCK
);


