CREATE TABLE iPurchase.STOCK AS 
WITH ITEMS AS (
	SELECT DISTINCT COMPANYID, SUBSIDIARYID, UPPER(ITEMID) AS ITEMID FROM iPurchase.PURCHPRICE_master_Filtered WHERE UNITPRICE IS NOT NULL
	UNION -- No queremos valores repetidos
	SELECT DISTINCT COMPANYID, SUBSIDIARYID, UPPER(ITEMID) AS ITEMID FROM iPurchase.ROUTES_master_Filtered
), withStock AS (
	SELECT *, 
	CASE 
	    WHEN LEFT(ITEMID, 3) = '420' THEN FLOOR(RANDOM()*(40000-0)+0) -- Rodillos
	    ELSE FLOOR(RANDOM()*(2000-0)+0)
	END AS STOCK
	FROM ITEMS
), set0sInStock AS (
	SELECT COMPANYID, SUBSIDIARYID, ITEMID, 
	CASE 
	    WHEN RANDOM() <= 0.25 THEN 0
	    ELSE STOCK
	END AS STOCK
	FROM withStock
)SELECT *
FROM set0sInStock;



