CREATE TABLE iPurchase.STANDARDCOST AS 
SELECT t1.MyBOMITEMID, t1.BOMITEMID, t1."BOMCATALOG",t1.SUBSIDIARYID, t2.UNITPRICE  FROM 
(SELECT DISTINCT MyBOMITEMID, BOMITEMID, "BOMCATALOG", SUBSIDIARYID FROM iPurchase.BOM_NoSustitutives) t1
LEFT JOIN iPurchase.STANDARDCOST_master t2
ON UPPER(t1.BOMITEMID)=UPPER(t2.ITEMID) AND t1.SUBSIDIARYID = t2.SUBSIDIARYID;