-- Crear la tabla con los campos necesarios de las BOMs
CREATE TABLE BOM_fewDATA_Filtered AS
SELECT BOMID, COMPANYID, SUBSIDIARYID, ITEMID, PARENTBOMITEMID, BOMITEMID, 
	"LEVEL", PRIORITY, PMFPLANGROUPID, MAXIBOQTY, UNITID, BOMREALQTY,
	ORDERTYPE, DEFAULTORDERTYPETREE, ITEMPATH, "PATH", "CATALOG", BOMCATALOG 
FROM BOM_fewDATA
WHERE APPROVED = TRUE
ORDER BY BOMID, COMPANYID, SUBSIDIARYID, "LEVEL";



-- Contar las diferentes BOMs
SELECT COUNT(*) AS NBOMs
FROM (SELECT DISTINCT BOMID, COMPANYID, SUBSIDIARYID FROM BOM_fewDATA) as t1;

SELECT * FROM iPurchase.BOM_fewDATA_Filtered 
WHERE BOMITEMID  = '41010372171089' AND PRIORITY = 1;