
-- Items de fabricacion y compra
SELECT  
BOMITEMID, MyBOMITEMID, ROUTEID, LINEROUTEID, RUNTIME_COST, SETUP_COST, rmf.CURRENCYCODE, rmf.MOQs AS MOQ_Fabricacion,
SUPPLIERID,   
CASE WHEN t3.CURRENCYCODE = 'USD' THEN t3.UNITPRICE*t3.EXCHANGERATE_EUR ELSE t3.UNITPRICE END AS UNITPRICE_Compra, t3.CURRENCYCODE_LOCAL, -- Cambio a euros
COUNTRY, LEADTIME, t3.MOQs AS MOQ_Compra
FROM iPurchase.ROUTES_master_Filtered rmf
INNER JOIN
(SELECT * FROM 
(SELECT DISTINCT BOMITEMID, MyBOMITEMID FROM iPurchase.BOM_NoSustitutives) t1
INNER JOIN 
(SELECT * FROM iPurchase.PURCHPRICE_master_Filtered) t2
ON UPPER(t1.BOMITEMID) = UPPER(t2.ITEMID)
WHERE t2.UNITPRICE IS NOT NULL
) t3
ON UPPER(rmf.ITEMID)= UPPER(t3.ITEMID)
WHERE rmf.MOQs IS NOT NULL
;


-- Items de compra
SELECT BOMITEMID, MyBOMITEMID, 
SUPPLIERID,   
CASE WHEN t3.CURRENCYCODE = 'USD' THEN t3.UNITPRICE*t3.EXCHANGERATE_EUR ELSE t3.UNITPRICE END AS UNITPRICE_Compra, t3.CURRENCYCODE_LOCAL, -- Cambio a euros
COUNTRY, LEADTIME, t3.MOQs AS MOQ_Compra
FROM iPurchase.ROUTES_master_Filtered rmf
RIGHT JOIN
(SELECT * FROM 
(SELECT DISTINCT BOMITEMID, MyBOMITEMID FROM iPurchase.BOM_NoSustitutives) t1
INNER JOIN 
(SELECT * FROM iPurchase.PURCHPRICE_master_Filtered) t2
ON UPPER(t1.BOMITEMID) = UPPER(t2.ITEMID)
-- WHERE t2.UNITPRICE IS NOT NULL
) t3
ON UPPER(rmf.ITEMID)= UPPER(t3.ITEMID)
WHERE rmf.ITEMID IS NULL OR rmf.MOQs IS NULL
;

-- Items de fabricacion
SELECT BOMITEMID, MyBOMITEMID, ROUTEID, LINEROUTEID, RUNTIME_COST, SETUP_COST, t3.CURRENCYCODE, t3.MOQs AS MOQ_Fabricacion FROM 
(SELECT * FROM 
(SELECT DISTINCT BOMITEMID, MyBOMITEMID FROM iPurchase.BOM_NoSustitutives) t1
INNER JOIN 
(SELECT * FROM iPurchase.ROUTES_master_Filtered) t2
ON UPPER(t1.BOMITEMID) = UPPER(t2.ITEMID)) t3
LEFT JOIN 
(SELECT * FROM iPurchase.PURCHPRICE_master_Filtered) t4
ON UPPER(t3.ITEMID)= UPPER(t4.ITEMID)
WHERE t4.UNITPRICE IS NULL
;