-- Crear la tabla con los campos necesarios de las COMPRAS
CREATE TABLE iPurchase.PURCHPRICE_master_Filtered AS
WITH partialTable AS (
SELECT ITEMID, COMPANYID, SUBSIDIARYID, SUPPLIERID, UNITPRICE, CURRENCYCODE, CURRENCYCODE_LOCAL,
	EXCHANGERATE_EUR, EXCHANGERATE_USD, EXCHANGERATE_LOCAL, FROMQUANTITY, TOQUANTITY, 
	SCALEDROW/1000000 AS ORDERSCALING
FROM iPurchase.PURCHPRICE_master
ORDER BY ITEMID, COMPANYID, SUBSIDIARYID, ORDERSCALING
),
CountryTable AS 
(
    SELECT ITEMID, pmf.COMPANYID, pmf.SUBSIDIARYID, pmf.SUPPLIERID, t2.COUNTRY, UNITPRICE, CURRENCYCODE, CURRENCYCODE_LOCAL,
        EXCHANGERATE_EUR, EXCHANGERATE_USD, EXCHANGERATE_LOCAL, FROMQUANTITY, TOQUANTITY, 
        ORDERSCALING
    FROM partialTable pmf
    LEFT JOIN
    (SELECT SUPPLIERID, COMPANYID, SUBSIDIARYID, COUNTRY  FROM fersadv.Supplier_ALL) AS t2
    ON pmf.supplierID = t2.SUPPLIERID AND pmf.SUBSIDIARYID = t2.SUBSIDIARYID
), 
subquery AS (
    SELECT *, 
    CASE 
        WHEN COUNTRY IN ('LTU', 'ITA', 'ESP', 'GBR', 'TUR', 'POL', 'DEU', 'NLD', 'SWE', 'IRL', 'MKD', 'PRT', 'FRA', 'AUT', 'LUX') THEN 0
        WHEN COUNTRY = 'CHN' THEN 6
        WHEN COUNTRY = 'IND' THEN 4
        ELSE 2
    END AS LEADTIME
    FROM CountryTable
) SELECT partialTable.ITEMID, partialTable.COMPANYID, partialTable.SUBSIDIARYID, partialTable.SUPPLIERID, 
	partialTable.UNITPRICE, partialTable.CURRENCYCODE, partialTable.CURRENCYCODE_LOCAL,
	partialTable.EXCHANGERATE_EUR, partialTable.EXCHANGERATE_USD, partialTable.EXCHANGERATE_LOCAL, 
	partialTable.FROMQUANTITY, partialTable.TOQUANTITY, 
	partialTable.ORDERSCALING, subquery.COUNTRY, subquery.LEADTIME
FROM 
partialTable
LEFT JOIN
subquery
ON partialTable.ITEMID = subquery.ITEMID AND partialTable.ORDERSCALING = subquery.ORDERSCALING
;


-- Ahora hay que fijar los valores de SUPPLIERID = '' segun las indicaciones dadas
UPDATE iPurchase.PURCHPRICE_master_Filtered
SET SUPPLIERID = 'P0100083',
    COUNTRY = 'CHN',
    LEADTIME = 6
WHERE SUPPLIERID = '';


