-- Crear la tabla con los campos necesarios de las COMPRAS
CREATE TABLE iPurchase.PURCHPRICE_master_Filtered AS
WITH partialTable AS (
SELECT ITEMID, COMPANYID, SUBSIDIARYID, SUPPLIERID, UNITPRICE, CURRENCYCODE, CURRENCYCODE_LOCAL,
	EXCHANGERATE_EUR, EXCHANGERATE_USD, EXCHANGERATE_LOCAL, FROMQUANTITY, TOQUANTITY, 
	SCALEDROW/1000000 AS ORDERSCALING
FROM iPurchase.PURCHPRICE_master
ORDER BY ITEMID, COMPANYID, SUBSIDIARYID, ORDERSCALING
),
CountryTable AS 
(
    SELECT ITEMID, pmf.COMPANYID, pmf.SUBSIDIARYID, pmf.SUPPLIERID, t2.COUNTRY, UNITPRICE, CURRENCYCODE, CURRENCYCODE_LOCAL,
        EXCHANGERATE_EUR, EXCHANGERATE_USD, EXCHANGERATE_LOCAL, FROMQUANTITY, TOQUANTITY, 
        ORDERSCALING
    FROM partialTable pmf
    LEFT JOIN
    (SELECT SUPPLIERID, COMPANYID, SUBSIDIARYID, COUNTRY  FROM fersadv.Supplier_ALL) AS t2
    ON pmf.supplierID = t2.SUPPLIERID AND pmf.SUBSIDIARYID = t2.SUBSIDIARYID
), 
subquery AS (
    SELECT *, 
    CASE 
        WHEN COUNTRY IN ('BEL', 'DEU', 'PRT', 'MKD', 'CZE', 'AUT', 'SMR', 'FRA', 'LUX', 'BLR', 
        				'HRV', 'FIN', 'RUS', 'LIE', 'SWE', 'IRL', 'NLD', 'EST', 'GRC', 'LVA', 'SVK', 
        				'DNK', 'LTU', 'ITA', 'ROU', 'SVN', 'SRB', 'CHE', 'ESP', 'HUN', 'BGR', 'POL') THEN 0 -- Países en Europa
        WHEN COUNTRY = 'CHN' THEN 6
        WHEN COUNTRY = 'IND' THEN 4
        ELSE 2
    END AS LEADTIME
    FROM CountryTable
), allButMOQ AS
(SELECT partialTable.ITEMID, partialTable.COMPANYID, partialTable.SUBSIDIARYID, partialTable.SUPPLIERID, 
	partialTable.UNITPRICE, partialTable.CURRENCYCODE, partialTable.CURRENCYCODE_LOCAL,
	partialTable.EXCHANGERATE_EUR, partialTable.EXCHANGERATE_USD, partialTable.EXCHANGERATE_LOCAL, 
	partialTable.FROMQUANTITY, partialTable.TOQUANTITY, 
	partialTable.ORDERSCALING, subquery.COUNTRY, subquery.LEADTIME
FROM 
partialTable
LEFT JOIN
subquery
ON partialTable.ITEMID = subquery.ITEMID AND partialTable.ORDERSCALING = subquery.ORDERSCALING
), MOQPURCHASES AS(
	SELECT PM.COMPANYID, PM.SUBSIDIARYID, PM.ITEMID, 
	CASE 
        WHEN MOQs.MOQ = 0 THEN 1 --Se asume que si la MOQ es 0 es porque no hay y por tanto es lo mismo que asignarle el valor 1
        ELSE MOQs.MOQ 
        END AS MOQs 
	FROM
	(SELECT DISTINCT COMPANYID, SUBSIDIARYID, ITEMID FROM allButMOQ) AS PM
	LEFT JOIN
	(SELECT COMPANYID, SUBSIDIARYID, ITEMID, MOQ FROM fersadv.Item_ALL) AS MOQs
	ON PM.COMPANYID = MOQs.COMPANYID AND PM.SUBSIDIARYID = MOQs.SUBSIDIARYID AND PM.ITEMID = MOQs.ITEMID
) SELECT abm.*, moq.MOQs
FROM 
allButMOQ abm LEFT JOIN MOQPURCHASES moq
ON abm.ITEMID = moq.ITEMID;


-- Ahora hay que fijar los valores de SUPPLIERID = '' segun las indicaciones dadas
UPDATE iPurchase.PURCHPRICE_master_Filtered
SET SUPPLIERID = 'P0100083',
    COUNTRY = 'CHN',
    LEADTIME = 6
WHERE SUPPLIERID = '';


