CREATE TABLE BOM_fewDATA_MyIDs AS 
WITH NoSustitutives AS (
    SELECT * FROM iPurchase.BOM_fewDATA_Filtered
),
NEWBOMITEMID AS (
    SELECT
        BOMITEMID,
        ROW_NUMBER() OVER (ORDER BY BOMITEMID) AS MyBOMITEMID
    FROM
        (SELECT DISTINCT BOMITEMID FROM NoSustitutives) AS distinct_bomitems
),
NEWBOMID AS (
    SELECT
        BOMID,
        ROW_NUMBER() OVER (ORDER BY BOMID) AS MyBOMID
    FROM
        (SELECT DISTINCT BOMID FROM NoSustitutives) AS distinct_bomid
),
NEWITEMID AS (
    SELECT
        ns.ITEMID,
        ni.MyBOMITEMID AS MyITEMID
    FROM
        NoSustitutives ns
    LEFT JOIN NEWBOMITEMID ni ON ns.ITEMID = ni.BOMITEMID
),
NEWPARENTID AS (
    SELECT
        ns.PARENTBOMITEMID,
        np.MyBOMITEMID AS MyPARENTBOMITEMID
    FROM
        NoSustitutives ns
    LEFT JOIN NEWBOMITEMID np ON ns.PARENTBOMITEMID = np.BOMITEMID
)
SELECT
	ns.BOMID,
	nb.MyBOMID,
    ns.COMPANYID,
    ns.SUBSIDIARYID,
    ns.ITEMID,
    t1.MyITEMID,
    ns.PARENTBOMITEMID,
    t2.MyPARENTBOMITEMID,
    ns.BOMITEMID,
    ni.MyBOMITEMID,
    ns.LEVEL,
    ns.PRIORITY,
    ns.PMFPLANGROUPID,
    ns.MAXIBOQTY,
    ns.UNITID,
    ns.BOMREALQTY,
    ns.ORDERTYPE,
    ns.DEFAULTORDERTYPETREE,
    ns.ITEMPATH,
    ns.PATH,
    ns.CATALOG,
    ns.BOMCATALOG
FROM
NoSustitutives ns
LEFT JOIN NEWBOMITEMID ni ON ns.BOMITEMID = ni.BOMITEMID
LEFT JOIN NEWBOMID nb ON ns.BOMID = nb.BOMID
LEFT JOIN (SELECT DISTINCT ITEMID, MyITEMID FROM NEWITEMID) t1 ON ns.ITEMID = t1.ITEMID
LEFT JOIN (SELECT DISTINCT PARENTBOMITEMID, MyPARENTBOMITEMID FROM NEWPARENTID) t2 ON ns.PARENTBOMITEMID = t2.PARENTBOMITEMID;

