-- Crear la tabla con los campos necesarios de la FABRICACION
CREATE TABLE iPurchase.ROUTES_master_Filtered AS
SELECT ITEMID, ROUTEID, LINEROUTEID, COMPANYID, SUBSIDIARYID, RUNTIME_COST, SETUP_COST, CURRENCYCODE 
FROM iPurchase.ROUTES_master
WHERE APPROVED IS TRUE AND ACTIVE IS TRUE AND "LEVEL" = 0
ORDER BY ITEMID, ROUTEID, LINEROUTEID
;